name: Build-windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  VULKAN_SDK_VERSION: 1.3.275.0

jobs:
  Windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }
          - { sys: clang64, env: clang-x86_64 }

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ${{matrix.sys}}
        install: >-
          git
          wget
        pacboy: >-
          cmake:p
          toolchain:p
          libsigc++:p
          yaml-cpp:p
          glfw:p
          catch:p
          vulkan-headers:p
          vulkan-loader:p
          shaderc:p
          glslang:p
          spirv-tools:p
          ffts:p
          hidapi:p
          libpng:p

    - name: Install WiX
      if: ${{ matrix.sys == 'ucrt64' }}
      run: |
        choco install wixtoolset --force
      shell: cmd

    - name: Build And Dist
      if: ${{ matrix.sys == 'ucrt64' }}
      run: |
        mkdir build
        cd build
        cmake .. -DWIXPATH="C:\Program Files (x86)\WiX Toolset v3.14\bin" -DBUILD_TESTING=ON -GNinja
        ninja

    - name: Build Only
      if: ${{ matrix.sys != 'ucrt64' }}
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_TESTING=ON -GNinja
        ninja

    - name: Test
      if: ${{ false }}
      shell: msys2 {0}
      run: |
        ninja test

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ngscopeclient-build-windows-${{ runner.os }}-${{ matrix.env }}-${{ github.job }}
        path: build

    # - name: Upload Artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: glscopeclient-windows-${{ runner.os }}-${{ github.job }}
    #     path: msys2/*.zst

    - name: Upload Artifacts (ngscopeclient portable zip)
      if: ${{ matrix.sys == 'ucrt64' }}
      uses: actions/upload-artifact@v4
      with:
        name: ngscopeclient-windows-portable-${{ runner.os }}-${{ github.job }}
        path: build/dist/ngscopeclient*.zip

    - name: Upload Artifacts (ngscopeclient MSI)
      if: ${{ matrix.sys == 'ucrt64' }}
      uses: actions/upload-artifact@v4
      with:
        name: ngscopeclient-${{ runner.os }}-${{ github.job }}.msi
        path: build/dist/ngscopeclient*.msi
